FROM node:22-bookworm-slim

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

RUN corepack enable

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml ./

RUN if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile --fetch-timeout=900000; else pnpm install --fetch-timeout=900000; fi

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev"]
